# Workflow name
name: GitHub Continuous Deployment

# Auto Trigger by Commit on main Branch
on: 
  push:
    branches: 'main'

# The list of jobs to run 
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # 1. Configure AWS credentials      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      # 2. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
      
      # 3. Setup Node
      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # 4. Setup Cache
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 5. Build Angular
      - name: Build Angular Application
        run: |
          cd surfer-kim-blog
          npm install -g @angular/cli
          npm install
          ng build
          
      # 6. Copy to S3 bucket.
      - name: Copy to S3 Bucket
        run: |
          cd surfer-kim-blog
          aws s3 cp ./dist/surfer-kim-blog/browser s3://${AWS_S3_URL} --recursive
